# Single-container PWA deployment

services:
  # All-in-one PWA service (backend serves frontend)
  pwa-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:${PORT:-3001}
    container_name: pwa-app
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost:3001
      - CORS_ORIGIN=http://localhost:3001
    ports:
      - "${PORT:-3001}:3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
